# Generated by Django 4.1.5 on 2023-01-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_salecount_alter_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
