# Generated by Django 4.1.5 on 2023-01-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='saleCount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default=1, max_length=255, null=True),
        ),
    ]
