# Generated by Django 4.1.6 on 2023-02-19 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_salecount_remove_product_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street_address_1', models.CharField(max_length=255)),
                ('street_address_2', models.CharField(blank=True, max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=31)),
                ('order_notes', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='OptionalShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('street_address_1', models.CharField(blank=True, max_length=255)),
                ('street_address_2', models.CharField(blank=True, max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=30)),
                ('order_notes', models.TextField(blank=True, max_length=1000)),
                ('billingaddress', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.billingaddress')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='interests',
            field=models.ManyToManyField(blank=True, to='store.interest'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='optionalshippingaddress',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.customer'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='store.billingaddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='optional_shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.optionalshippingaddress'),
        ),
    ]
