# Generated by Django 4.1.6 on 2023-02-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_billingaddress_optionalshippingaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='optionalshippingaddress',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.billingaddress'),
        ),
        migrations.AddField(
            model_name='customer',
            name='optional_shipping_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.optionalshippingaddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.billingaddress'),
        ),
    ]
