# Generated by Django 4.1.6 on 2023-02-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_billingaddress_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_billing_address', to='store.billingaddress'),
        ),
    ]
