# Generated by Django 4.1.6 on 2023-02-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_billingaddress_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalshippingaddress',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='optional_shipping_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_optional_shipping_address', to='store.optionalshippingaddress'),
        ),
    ]
