# Generated by Django 4.1.6 on 2023-02-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_customer_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='billing_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_billing_address', to='store.billingaddress'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='optional_shipping_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_optional_shipping_address', to='store.optionalshippingaddress'),
        ),
    ]
