# Generated by Django 4.1.6 on 2023-02-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_customer_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionalshippingaddress',
            name='billingaddress',
        ),
    ]
