# Generated by Django 4.1.5 on 2023-02-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_optionalshippingaddress_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalshippingaddress',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionalshippingaddress',
            name='phone',
            field=models.CharField(default='1234567890', max_length=31),
            preserve_default=False,
        ),
    ]
