# Generated by Django 4.1.6 on 2023-03-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_optionalshippingaddress_order_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionalshippingaddress',
            name='order_notes',
        ),
    ]
