# Generated by Django 4.1.6 on 2023-03-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_cartitem_price_after_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price_after_discount',
            new_name='final_price_after_discount',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_after_discount',
            new_name='final_price_after_discount',
        ),
    ]
