# Generated by Django 4.1.6 on 2023-03-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_rename_price_after_discount_cartitem_final_price_after_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
