# Generated by Django 4.1.6 on 2023-03-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_cartitem_variation_orderitem_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='optionalshippingaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=31),
        ),
    ]
