# Generated by Django 4.1.6 on 2023-03-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_customer_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='discount_percentage',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount_percentage',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='discount_percentage',
            new_name='discount',
        ),
    ]
