# Generated by Django 4.1.6 on 2023-04-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='type',
            field=models.CharField(default='tablets', max_length=255),
            preserve_default=False,
        ),
    ]
