# Generated by Django 4.1.6 on 2023-04-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name_plural': 'Categories'},
        ),
    ]
