# Generated by Django 4.2.5 on 2023-09-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0041_alter_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_charge_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
