# Generated by Django 4.2.5 on 2023-09-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0043_stripecharge"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StripeCharge",
        ),
    ]
