# Generated by Django 4.2.5 on 2023-10-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0044_delete_stripecharge"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="stripe_sub_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
