# Generated by Django 4.2.5 on 2023-10-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0045_customer_stripe_customer_id_customer_stripe_sub_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="stripe_sub_id",
        ),
    ]
