# Generated by Django 4.2.5 on 2023-10-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0046_remove_customer_stripe_sub_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="interests",
            field=models.ManyToManyField(blank=True, null=True, to="store.interest"),
        ),
    ]
