# Generated by Django 4.1.6 on 2023-04-23 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='graphics/logo/')),
                ('graphics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='core.graphics')),
            ],
            options={
                'verbose_name_plural': 'Logos',
            },
        ),
        migrations.CreateModel(
            name='HomePageSmallPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='graphics/home_page_small_picture/')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('graphics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_small_picture', to='core.graphics')),
            ],
            options={
                'verbose_name_plural': 'Home Page Small Pictures',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='graphics/home_page_slider/')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('graphics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_slider', to='core.graphics')),
            ],
            options={
                'verbose_name_plural': 'Home Page Sliders',
                'ordering': ['id'],
            },
        ),
    ]
