# Generated by Django 4.1.6 on 2023-04-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_graphics_logo_homepagesmallpicture_homepageslider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphics',
            options={'verbose_name_plural': 'Graphics'},
        ),
    ]
