# Generated by Django 4.1.6 on 2023-06-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_homepageicon"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField(blank=True, max_length=2550, null=True)),
            ],
            options={
                "verbose_name_plural": "Contact Form Entries",
                "ordering": ["id"],
            },
        ),
    ]
