# Generated by Django 4.1.6 on 2023-06-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_contactformentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_phone",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Business Details",
            },
        ),
        migrations.AlterField(
            model_name="homepageicon",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="graphics/home_page_icon/"
            ),
        ),
    ]
