# Generated by Django 4.1.6 on 2023-06-23 15:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_businessdetails_alter_homepageicon_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessdetails",
            name="refunds_and_returns",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
