# Generated by Django 4.1.5 on 2023-01-22 18:54

import blog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/images', validators=[blog.validators.validate_file_size])),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='blog.blogpost')),
            ],
        ),
    ]
