# Generated by Django 4.1.5 on 2023-01-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['last_update']},
        ),
    ]
